# Site settings
title: "B. Font Garcia personal webpage"
description: "B. Font Garcia persona webpage"
url: "https://www.b-fg.github.io"
author:
  name: "Bernat Font Garcia"
  email: "b.fontgarcia@soton.ac.uk"
  url: "https://www.b-fg.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site/research
permalink: /:title
paginate: 5
paginate_path: "/research/page:num/"

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: true
custom_nav_footer: false
reverse: false
